### ISSUE TITLE
Support proxy config (httr or RCurl or use internet2)

### ISSUE THREAD

**Issue by juancentro** [rstudio/shinyapps#121]
I can't `setAccountInfo` because I'm behind a proxy. I can use `httr::set_config(use_proxy())` to make `devtools::install_github()` work, and RStudio installs packages normally using internet2.dll, and I can also use `RCurl` when I need it. But I don't find a way to have `shinyapps` use some proxy config

**Comment by shelmich** [comment]
I've been diving into this problem, as I'm having the same one. in http.R, it looks like it talks to api.shinyapps.io using the httpRCurl function. specifically, on line 295-297, we see RCurl::getURL(url, .opts = options, write = textGatherer).

When looking at how to use RCurl to get past a proxy, you usually have to do something like in Method 4 as shown here: http://stackoverflow.com/questions/6467277/proxy-setting-for-r

Specifically:
curl <- getCurlHandle()
curlSetOpt(.opts = list(proxy = '999.99.99.99:8080'), curl = curl)
Res <- getURL('http://www.cricinfo.com', curl = curl)


so it looks like there needs to be an input that takes the proxy info, then passes it into whatever getURL function gets called, and the curl handle needs to be adjusted accordingly.

**Comment by kippandrew** [comment]
Have you taken a look at the documentation for using proxies with shinyapps?

```R
library(shinyapps)
?shinyappsProxies
```

**Comment by juancentro** [comment]
That worked for me! Used options(RCurlOptions = list(proxy =
"http://myproxy:myproxyport")) and now setAccountInfo works
