### ISSUE TITLE
Application depends on package "rmarkdown" but it is not installed?

### ISSUE THREAD

**Issue by xinglongjian** [rstudio/shinyapps#123]
I deployed my project to shinyapps.io and I get this error:
`Application depends on package "rmarkdown" but it is not installed. Please resolve before continuing.`
my project 's URL:https://xinglongjian.shinyapps.io/RShinyDemos
but I **get this error again** when  I add **"require(markdown)"** to my ui.R.

**Comment by kippandrew** [comment]
Hi,

You need to make sure you rmarkdown installed on your machine before you can use it:

install.packages('rmarkdown')

-Andy

**Comment by xinglongjian** [comment]
It's my mistake！I did't install this package.Thanks for @kippandrew
