### ISSUE TITLE
R 3.1.2 devtools::install_github('rstudio.shinyapps') is not working

### ISSUE THREAD

**Issue by seibeldb** [rstudio/shinyapps#129]
I keep getting this error.  What can I do to fix this?

> devtools::install_github('rstudio.shinyapps')
Error in username %||% getOption("github.user") %||% stop("Unknown username.") : 
  Unknown username.

**Comment by seibeldb** [comment]
I am using:
Version 0.98.1091 – © 2009-2014 RStudio, Inc.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko)
and
> version
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          1.2                         
year           2014                        
month          10                          
day            31                          
svn rev        66913                       
language       R                           
version.string R version 3.1.2 (2014-10-31)
nickname       Pumpkin Helmet              
>

**Comment by jjallaire** [comment]
Try a slash as the delimiter: devtools::install_github('rstudio/shinyapps')

**Comment by seibeldb** [comment]
perfect.  Thanks.
