### ISSUE TITLE
Issues deploying apps to shinyapps.io: setAccountInfo and Packages not available in repository or locally

### ISSUE THREAD

**Issue by pssguy** [rstudio/shinyapps#130]
Couple of issues
No reply on googlegroup so trying here

 a) I'm looking to deploy an update to an existing app https://pssguy.shinyapps.io/worldBank/ but when I use the
publish button in RStudio am getting 

      building: Building package: sparkline
    ################################## Begin Log ################################## 
    Error: You must register an account using setAccountInfo prior to proceeding.

I have recently gone through the setAccountInfo() process and am able to deploy other apps
Have restarted R , rebooted to no avail

Going via console, I also have a problem

> library(shinyapps)
> deployApp("worldBank")
Error in lint(appDir) : No directory at path 'worldBank'
> getwd()
[1] "C:/Users/.../R/worldBank"

b) For any deployment I am getting new warning messages
e.g.

        In addition: Warning messages:
        1: In FUN(c("rmarkdown", "shiny", "rgdal", "leaflet", "dplyr", "WDI",  :
          Package 'leaflet' not available in repository or locally
        2: In FUN(c("rmarkdown", "shiny", "rgdal", "leaflet", "dplyr", "WDI",  :
          Package 'DT' not available in repository or locally
        3: In FUN(c("rmarkdown", "shiny", "rgdal", "leaflet", "dplyr", "WDI",  :
          Package 'sparkline' not available in repository or locally

These packages are on github so am not sure what the problem is here?

    R version 3.1.2 (2014-10-31)
    Platform: x86_64-w64-mingw32/x64 (64-bit)

    locale:
    [1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
    [3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
    [5] LC_TIME=English_Canada.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] shinyapps_0.3.63

    loaded via a namespace (and not attached):
    [1] bitops_1.0-6     digest_0.6.8     htmltools_0.2.6  RCurl_1.95-4.5   RJSONIO_1.3-0   
    [6] rmarkdown_0.5.1  rsconnect_0.3.73 tools_3.1.2      yaml_2.1.13

**Comment by kippandrew** [comment]
Hi,

The first argument to deployApp() is a directory.

Try:

`setwd('path/to/your/application')`

`deployApp()`

Does that work?

**Comment by pssguy** [comment]
@kippandrew 

Thanks
> library(shinyapps)
> deployApp()

does get things going so I can go that route - although the publsih via RStudio issue is still outstanding

I do hit 
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘htmltools’
ERROR: lazy loading failed for package ‘sparkline’
* removing ‘/usr/local/lib/R/site-library/sparkline’

but I think that is an htmltools rather than shinyapp issue

**Comment by jjallaire** [comment]
The problem is that the sparkline package doesn't list the htmlwidgets
package as a dependency (and it does carry this dependency). You can work
around this by creating a side file called dependencies.R and inserting
this into it:

require(htmlwidgets)

**Comment by pssguy** [comment]
@jjallaire 

Created the file dependencies.R, in the same directory, with the one line in it but on deploying

    ** preparing package for lazy loading
    Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
      there is no package called ‘htmltools’
    ERROR: lazy loading failed for package ‘sparkline’
    * removing ‘/usr/local/lib/R/site-library/sparkline’
    ################################### End Log ################################### 
    Error: Unhandled Exception: Child Task 7779878 failed: Error building image: Error building sparkline             (1.0). Build exited with non-zero status: 1
 
Did I misunderstand you?

**Comment by jjallaire** [comment]
You also need to actually install the packages htmlwidgets and htmltools.
If that doesn't solve the problem I'm at a complete loss as to what's going
on.

**Comment by pssguy** [comment]
You kinda lost me there 

I do have them installed on my local system but can run the app fine locally
without calling them specifically

I added 
    library(htmltools)
    library(htmlwidgets)

to an ..Rmd file but get the same error message on deployment

Do you mean I literally have to install them in the code like

install.packages("htmlwidgets")
install.packages("htmltools")
??
that would be unlike any other package i use
e.g. library(dplyr)

**Comment by kippandrew** [comment]
It's possible even with the dependencies manually specified, the shinyapps
dependency resolver is installing the packages in the wrong order. Since
sparklines is missing the dependancies in its DESCRIPTION file, and it has
no other dependencies, it is maybe being installed *before* htmlwidgets.

**Comment by jjallaire** [comment]
That makes perfect sense. I think you should ask the maintainer of
sparklines to include the requisite Depends in the package DESCRIPTION file
(or fork and make the change and then send a PR).

**Comment by pssguy** [comment]
I have  - but he has a lot on his plate!

So I just have to add
Depends: htmltools 

to the DESCRIPTION file I have forked?
I have not done a PR before

**Comment by jjallaire** [comment]
I'd add Depends: htmlwidgets

**Comment by pssguy** [comment]
Cheers
I'm sure Ramnath will correct, if necessary

**Comment by jjallaire** [comment]
it turns out I'm actually a committer to that repo so I'll make the change!

**Comment by jjallaire** [comment]
I put a PR in to make the change. In the meantime you can install from here:

devtools::install_github("jjallaire/sparkline", ref = "patch-1")

**Comment by pssguy** [comment]
Thanks
 Looks good
