### ISSUE TITLE
Shinyapps publication error

### ISSUE THREAD

**Issue by willgearty** [rstudio/shinyapps#131]
Posted this on the google group, but I figured this might be a better place to look for answers...

I was trying to publish my app to shinyapps.io, but I got the following error:
```r
Preparing to deploy application...DONE
Uploading application bundle...Error: Unable to retrieve package records for the following packages:
- "ape", "xtable"
Execution halted
```
Any thoughts? Could this be due to dev versions of these packages?
The app is running fine locally...

Thanks in advance,
Will

**Comment by willgearty** [comment]
Never mind, I realized that one (ape) was a dev version that wasn't on CRAN and the other one (xtable) was a dev version that was on R-forge but also not on CRAN. I removed both packages and then installed the CRAN versions and it worked perfectly.

**Comment by englianhu** [comment]
above answer and [Shinyapps publication error](https://groups.google.com/forum/#!msg/shiny-discuss/p_hJApAH-LY/NpPyURAZ_FoJ) is works.
