### ISSUE TITLE
Maximum supported R version is: 3.1.2

### ISSUE THREAD

**Issue by booysej** [rstudio/shinyapps#136]
R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

> library(shinyapps)
> deployApp();

Error: Unhandled Exception: Child Task 16894008 failed: Error parsing manifest: Maximum supported R version is: 3.1.2

**Comment by yvanrichard** [comment]
Same here and I need to deploy my app today... It would be nice for shinyapps.io to be pro-active about the release of new R versions. Now that the new version became the default on the Ubuntu repo, I suspect there are a few other people out there also annoyed.

**Comment by CBarraford** [comment]
version 3.1.3 is now supported.
