### ISSUE TITLE
Hidden Menu Item

### ISSUE THREAD

**Issue by danmalter** [rstudio/shinyapps#137]
This issue is for the Shiny Dashboard layout.

With the new "Powered by RStudio" banner at the top of free apps, it pushes the dashboardHeader() down on the screen and as a result, if you have a dashboardHeader then it covers up the first menuItem on the sidebarMenu.  Before the RStudio logo was added, this was not an issue because the dashboardHeader was in that spot.

**Comment by kippandrew** [comment]
I believe we've fixed this (the branding bar is now served through an iFrame). Can you tell me if you are still having issues.

**Comment by danmalter** [comment]
It looks better, thanks.
