### ISSUE TITLE
Error when trying to deploy a shiny app

### ISSUE THREAD

**Issue by alexmathai** [rstudio/shinyapps#141]
Has anyone seen this error and know what to do about it? I've tried updating the shinyapps package, but it didn't fix the problem.  I have version 0.10.2.1 of shiny, and 0.3.61 of shinyapps, rstudio version 0.98.1074

Preparing to deploy application...Error: /v1/applications/?filter=account_id:18320&filter=name:nextword&count=100&offset=0 426 - shinyapps package out of date.

To update visit: https://github.com/rstudio/shinyapps

Execution halted

**Comment by kippandrew** [comment]
The latest version of the shinyapps package is 0.3.63. Have you tried updating to the latest version?

**Comment by alexmathai** [comment]
When I look at the update window in RStudio, shinyapps is not one of the packages that shows as needing an update.  I'm not sure why...

**Comment by kippandrew** [comment]
I believe that pane only looks examines CRAN packages. shinyapps package is not on CRAN so might not work correctly. You need to run:

```R
devtools::install_github("rstudio/shinyapps")
```

**Comment by alexmathai** [comment]
Yup, that was exactly the problem. I looked on GitHub after your previous message and updated manually.  Problem solved.  Good to know that the packages pane is only from CRAN (I also didn't know that shinyapps wasn't a part of CRAN).  Chalk it up to being a relative newbie to R.  Thanks a lot for your help Kip!!
