### ISSUE TITLE
Error on deploying: Maximum supported R version is: 3.1.3

### ISSUE THREAD

**Issue by RajuVarghese** [rstudio/shinyapps#142]
I am trying to deploy an app to shinyapps with the console command ...

shinyapps::deployApp ("tiapp")

and I get the error ...

Waiting for task: 27531530
  error: Parsing manifest
################################### End Log ################################### 
Error: Unhandled Exception: Child Task 27531532 failed: Error parsing manifest: Maximum supported R version is: 3.1.3

I am running RStudio on Linux (Ubuntu 14.04).

Thanks in advance.

Raju

**Comment by kippandrew** [comment]
Duplicates #141

**Comment by kippandrew** [comment]
We will be adding support for R 3.2.0 this week.

**Comment by kippandrew** [comment]
We deployed support for R 3.2.0 this morning. This should be all set.

**Comment by RajuVarghese** [comment]
Thanks.

Raju

**Comment by ckameni** [comment]
I am trying to publish an interactive markdown document  
and I get the error ...

Preparing to deploy application...DONE
Uploading application bundle...DONE
Deploying application: 48635...
Waiting for task: 46574515
  building: Processing bundle: 210125
  error: Parsing manifest
################################## Begin Log ################################## 
################################### End Log ################################### 
Fehler: Unhandled Exception: Child Task 46574522 failed: Error parsing manifest: Maximum supported R version is: 3.2.0

I am running RStudio on Linux (Ubuntu 14.04).

Thanks in advance.

Kameni

**Comment by CBarraford** [comment]
we added support for R 3.2.1 this morning. Please try again.
