### ISSUE TITLE
Possibly spurious error messages displayed after deployment

### ISSUE THREAD

**Issue by homerhanumat** [rstudio/shinyapps#144]
Using `shinyapps` version 0.3.63, I get error messages like this when deploying an app:

```
> deployApp()
Preparing to deploy application...DONE
Uploading application bundle...DONE
Deploying application: 10829...
Waiting for task: 28462540
  building: Parsing manifest
  building: Installing packages
  building: Installing files
  building: Pushing image: 168849
  deploying: Starting instances
  rollforward: Activating new instances
  terminating: Stopping old instances
Application successfully deployed to http://homer.shinyapps.io/SlowGoodness
Error in as.character(tools:::httpdPort) : 
  cannot coerce type 'closure' to vector of type 'character'
Error in as.character(tools:::httpdPort) : 
  cannot coerce type 'closure' to vector of type 'character'
Error in as.character(tools:::httpdPort) : 
  cannot coerce type 'closure' to vector of type 'character'
Error in as.character(tools:::httpdPort) : 
  cannot coerce type 'closure' to vector of type 'character'
```

But the apps themselves seem to deploy just fine.  This behavior started only today.  The only difference that is the same across all app deployments today is that I'm now using R 3.2 on this machine.

**Comment by jjallaire** [comment]
You may need to update RStudio to get rid of this error message (R 3.2
changed the way the port of the internal help server was accessed and
this required a change in RStudio). The very latest public release
(0.98.1103) should have this fix and the preview release
(http://www.rstudio.com/products/rstudio/download/preview/) will also
have the fix.

**Comment by homerhanumat** [comment]
Yep, that fixed it!

**Comment by YujiZhang** [comment]
Hi guys thanks for the discussion. Do you mean I need to use the preview version of Rstudio? I'm having the same problem. Shiny/Shinyapps/R are newest version, and Rstudio is the newest official version 0.98.953. Let me know please. Thanks a lot!

**Comment by YujiZhang** [comment]
I installed the preview version and it seems to have solved the problem. Thanks a lot guys!
