### ISSUE TITLE
Deploying an app that works on local computer doesn't work "url not supported"

### ISSUE THREAD

**Issue by janeshdev** [rstudio/shinyapps#150]
I have the following app that runs fine in my computer, however, it throws an error while deploying on the shinyapps: 

ui.R

    library(shiny)
    library(ggplot2)
    library(dplyr)
    library(rCharts)
    library(DT)
    library(htmlwidgets)
    library(shinyapps)
    # dataset <- ntctidecombined
    
    # Define UI for application that draws a histogram
    shinyUI(fluidPage(
      
      # Application title
      titlePanel("Seattle Society fund raise"),
      
      # Sidebar with a slider 
      sidebarLayout(position="left",
                    sidebarPanel( 
                
                    ),
                    mainPanel(
                      #       plotOutput('plot', height="700px"))
                      
                      tabsetPanel(
                        tabPanel("Plot", plotOutput("plot", width = "500px", height = "600px")),
                        tabPanel("Donors / Ticket buyers", tableOutput("donors")),
                        tabPanel("Table", tableOutput("table"))
                      ))
                    
      )
    ))

server.R

    library(shiny)
    library(ggplot2)
    library(dplyr)
    library(rCharts)
    library(DT)
    library(htmlwidgets)
    library(shinyapps)
    
    shinyServer(function(input, output) {
      
      #dataset <- load("ntctidecombined.Rda")
      dataset <- read.csv("https://dl.dropboxusercontent.com/u/9267938/Testspreadsheet.csv")
      
      dataset1 <- dataset %>% group_by(Category) %>% summarize(Sum = sum(Amount))
      
      output$plot <- renderPlot({
        dataset2 <- dataset1
    
      p1 <- ggplot(dataset1, aes(x = Category, y = Sum, fill = Category)) + 
      geom_bar(stat= "identity") + ylab("Total Amount (dollars)") +
      geom_text(aes(Category, Sum, label = Sum, vjust = -1.5)) + 
      coord_cartesian(ylim = c(0,10000))
      p1  
    
      })
      
       output$table <- renderTable(dataset1)
       output$donors <- renderTable(dataset)
      
    })

When I checked the logs in shinyapps I found that I got error as follows: 

`Error in file(file, "rt") : https:// URLs are not supported`.

I am trying to use the file that is on the dropbox so I want to use that file to automatically update the graphs and statistics. What is the best way to use data from web ?

**Comment by kippandrew** [comment]
What version of R are you using?

Are you running Windows?

I would also suggest posting this to the discussion group:
https://groups.google.com/forum/#!forum/shinyapps-users

**Comment by janeshdev** [comment]
Yes, I am running windows. Didn't know read.csv doesn't work on linux. I used `httr` package and the issue is fixed. 

I used the following code and it does work 

`dataset <- content(GET("http://dl.dropboxusercontent.com/u/9267938/Testspreadsheet.csv"))`
