### ISSUE TITLE
Package installation fails on shinyapps.io

### ISSUE THREAD

**Issue by klmr** [rstudio/shinyapps#152]
My package [klmr/modules](/klmr/modules) (not on CRAN) fails to install on shinyapps.io. Using it locally with Shiny works, by contrast.

Trying to deploy a minimal test application via `deployApp('.')` fails with the following error message:

```
[2015-05-21T13:30:17.839984528+0000] Building R package: modules (0.7.2)
/mnt/packages/build /mnt
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘modules’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in file(filename, "r", encoding = encoding) :
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '//.Rprofile': No such file or directory
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/modules’
```

I’ve created a [:link: gist with the test application](https://gist.github.com/klmr/8c23fbe0aedc9cab6592) I’m using. I’m assuming that the problem is related to the non-CRAN nature of the package: for instance, since the package is installed from source (from Github) it contains non-R related files that are crucial for development.

To solve this it would be helpful to know which exact requirements shinyapps has on packages, and how these can be made to work with Github hosted source packages.

This problem was originally reported to me by @ianfiske.

**Comment by kippandrew** [comment]
I took a look at your package and it looks like in the file `.Rprofile` you're attempting to source the file: `~/.Rprofile`. This is references a profile file the home directory which does not exist when shiny apps builds packages. You will have to remove this source call.

**Comment by klmr** [comment]
This sounds like a bug in Shiny, since it should ignore the `./.Rprofile` file! This file is for development only, it is not used in the package proper, and it is never sourced, nor should it. If Shiny attempts to source this file, that is a bug.

**Comment by kippandrew** [comment]
Its not specifically a Shiny problem. When shinyapps detects R dependencies for an application, it builds binary packages for those dependencies and caches them. These binaries are built using the command: `R CMD INSTALL --build ... `. By default, when R starts up, it sources the .Rprofile in the current directory (which in this case is the directory of the package). In your case, that file containers a reference to a file that is not guaranteed to exist. You could argue that we should not source .RProfile when building package binaries, but that may have other unindented side effects. IMO the safest thing to do here is make sure your package does not assume any files outside the package exist.

**Comment by klmr** [comment]
Oh my. I see. Thanks for pointing this out.

&lt;rant&gt;
This isn’t the first time I’ve noticed that the R package development process is completely broken — in this case, the problem is that it doesn’t allow distinguishing between a development and a deployment environment.
&lt;/rant&gt;

But yes, this isn’t a Shiny problem.

**Comment by gavinsimpson** [comment]
@klmr Just add `.Rprofile` to `.Rbuildignore` so it doesn't get included in the build at `R CMD build` time. If it's not supposed to be in the build then it is a bug in your sources that is allowing it to become part of the build.

**Comment by klmr** [comment]
@gavinsimpson Alas, [adding this file](https://github.com/klmr/modules/blob/ae3ac549e979d83c3f40683ed186231672607bfb/.Rbuildignore) doesn’t change the error at all. Incidentally, `R CMD build modules` (and `R CMD INSTALL --build modules`) also fails with the same error once I delete `~/.Rprofile`.

**Comment by gavinsimpson** [comment]
Are you sure it's picking up the change - the error is pretty clear about trying to read from that file?

**Comment by klmr** [comment]
@gavinsimpson That was my first suspicion. But the fact that it doesn’t work locally either, where I can verify the existence of the `.Rbuildignore` file, excludes this possibility. In fact, this is easily reproducible:

```bash
mkdir test
cd test
echo "stop('Y U INVOKE ME?')" > .Rprofile
echo .Rprofile > .Rbuildignore
R CMD build .
# Error: Y U INVOKE ME?
# Execution halted
```

I may be misunderstanding how `.Rbuildignore` is supposed to work but this is all I can find in the R-exts documentation.

**Comment by gavinsimpson** [comment]
This is actually the R process that you invoke via the `R CMD build .` call. You'd need to call this as `R  --no-init-file CMD build .` to stop the R process loading your local .Rprofile in order to build the tarball. Or to be doubly sure `R  --vanilla CMD build .`

**Comment by gavinsimpson** [comment]
I have no idea if you can trick shinyapps.io into doing the build that way?

This could be avoided if you didn't call the file `.Rprofile` and instead in your `Makefile` you arrange for it to start R and source the renamed file (which sources your `~/.Rprofile`). Assuming you don't start R manually in the source tree? If you do, perhaps create a new shell script that starts R and loads the renamed file? (I think the `-f` or `--file` arguments to `R` can be used for that.)

**Comment by klmr** [comment]
Sure, but with `--vanilla` I wouldn’t need the `.Rbuildignore` file anyway. And invoking the build with `--vanilla` (or `--no-init-file`) isn’t really what the user would want anyway, since it would ignore the local configuration completely. This just masks the problem rather than fixing it.

**Comment by gavinsimpson** [comment]
Yes, you *do* need `.Rbuildignore` --- you shouldn't be allowing R to build packages with files not intended for the package itself.

The problem here is really your bug to solve. R reads `.Rprofile` files. If you choose to instrument your development tree with such files, that is one thing but you shouldn't inflict that on the user. A strong argument could be made for your not including the `.Rprofile` file in the github repo,. Just carry it around locally --- that's what I do with files that I use to ease development but aren't needed or even wanted in the package sources, I just add them to `.gitignore`.

You should separate or isolate your development helper things from the sources or make sure that they don't interfere with the normal usage people expect. This is why shiny is failing; not because of a flaw in R's development process but because you included a file that R is known to read when invoked. If you don't want to use the correct flag to stop R from reading such files, the only option is for you to remove that file from the github repo.

**Comment by klmr** [comment]
Okay, granted, using `.Rbuildignore` is still needed (but does not fix this specific problem). My gripe is that it’s not doing its job in a really useful way. I maintain my criticism that it’s really R’s failing of not providing a way of isolating development and build environment. I’m currently working around this by renaming `.Rprofile` in the `master` branch of my project only (development happens in `develop`). That’s however quite an abuse of Git branches.

I disagree with your assessment about `.Rprofile` not belonging in the Git repository — in fact, I’d go as far as saying that this is simply wrong: Git’s job is to manage my development environment, not my build environment. That job falls to R (in a similar vein, it’s a shame that devtools insists on having the pre-compiled `Rd` help files inside the repository — that’s once again not really how Git should be used).

**Comment by gavinsimpson** [comment]
You can *easily* isolate your development and build environments. Don't invoke R in a location where you have a `.Rprofile` You *shouldn't need* this to build your package. Place your pkg sources in a subfolder and then that way you can have `.Rprofile` at the top level of git and the unadulterated source for the pkg in the sub folder. Running `R CMD build` on that from *anywhere* other than the git toplevel of your source will work fine.

I do this all the time with my packages; I have a Makefile that I use to automate build and check steps building documentation etc. I always have that Makefile step out of my source folder and build one folder up.

I should have been clearer; the way you have arrange your sources is what is wrong. If you want `.Rprofile` in git, you need to isolate it away from the R pkg sources. You can either not include it (it *isn't* part of the package sources so an argument can be made, but you differ, for it not to be here) or you can put the actual package source inside a folder in the repo.

As for devtools, well, it isn't an R package without Rd files. I agree that this is not ideal - you shouldn't have rendered files in the repo - but if you want to use github for things not foreseen by Linus when developing git, you need to show some flexibility.

**Comment by klmr** [comment]
> Don't invoke R in a location where you have a .Rprofile

As you can see from this very issue report, I simply have no control over how `R` is invoked during the build process.

> the way you have arrange your sources is what is wrong […] I always have that Makefile step out of my source folder and build one folder up.

R/devtools doesn’t give me any control over that. I’d love to have all my package source in a subfolder of my main development folder but devtools doesn’t allow that.

> If you want .Rprofile in git, you need to isolate it away from the R pkg sources

I’d love to do that but again it’s a (reasonable) constraint imposed by other tools that my development base directory is not a subdirectory of my project directory tree (in other words, I cannot put `.Rprofile` into a subdirectory of the root directory).

> but if you want to use github for things not foreseen by Linus when developing git, you need to show some flexibility

This has nothing to do with Git: devtools should simply build these files from the file source using Roxygen as needed.

**Comment by gavinsimpson** [comment]
>> Don't invoke R in a location where you have a .Rprofile

> As you can see from this very issue report, I simply have no control over how R is invoked during the build process.

And this is my point in the last paragraph; 95+% of R packages on github are set up so that what you see in the git toplevel for the repo is the pkg source and that this can be used *as is* to build the package.

If you deviate from that, things may fail as you've observed. This is just a fact of life. You live with it or you change the way you do things. This is github, not git.

>> the way you have arrange your sources is what is wrong […] I always have that Makefile step out of my source folder and build one folder up.

> R/devtools doesn’t give me any control over that. I’d love to have all my package source in a subfolder of my main development folder but devtools doesn’t allow that.

No-one said using **devtools** was compatible with every way or working. I don't use it at all and I have no problems building and maintaining packages. If I did use **devtools** I'd need to adapt to its opinionated way of doing things. Only I could decide if it is worth the effort to use it or not.

>> If you want .Rprofile in git, you need to isolate it away from the R pkg sources

> I’d love to do that but again it’s a (reasonable) constraint imposed by other tools that my development base directory is not a subdirectory of my project directory tree (in other words, I cannot put .Rprofile into a subdirectory of the root directory).

I never suggested this course of action.

>> but if you want to use github for things not foreseen by Linus when developing git, you need to show some flexibility

> This has nothing to do with Git: devtools should simply build these files from the file source using Roxygen as needed.

**devtools** does build them as needed but it needs somewhere to save them. It would complicate matters considerably to have it generate temporary folders to hold pkg sources in some rendered state in case you decided to build it. Also, you don't need to store the `./man` folder in git if you don't want to; just `.gitignore` it. My point was you can use git anyway you want but if you want to use github and use other tools that interface with github, you need to adapt to their expectations.

We should probably end this convo here (or take it elsewhere); I'm sure the shinyapps.io devs will be pleased if this thread went silent now its gone OT.
