### ISSUE TITLE
Publish button won't upload directories larger than 100mb to shinyapps

### ISSUE THREAD

**Issue by bradddd** [rstudio/shinyapps#153]
The deployApp() doesn't have any issues, but when clicking the "publish" button at the top of the preview window from Rstudio, you are presented with an error popup saying "Directory Too Large" and that the limit is 100mb.

The size limit appears to be in the Rstudio file: SessionRSConnect.R  
```
line 273: max_size <- 104857600   # 100MB
```

So it doesn't appear that this is an error but a limitation of Rstudio. Is there any plan to increase that within Rstudio now that the shinyapps limit has been bumped up to 1GB?

**Comment by jjallaire** [comment]
Thanks for reporting this. We've made a fix in RStudio which will appear shortly in our daily builds and then ultimately preview and final release of the next version. https://github.com/rstudio/rstudio/commit/8c86b98a0898292d043a4b50be591bc0759b3bd7
