### ISSUE TITLE
Find out whether code is running inside Shiny

### ISSUE THREAD

**Issue by klmr** [rstudio/shinyapps#157]
For my package [klmr/modules](/klmr/modules) I need to find out if code is being run from inside Shiny(Apps) or directly in R/via a script. Ultimately, this is necessary in order to find the path of the R source file that is calling the code.

At the moment, I am implementing this check by walking up the call stack to find out whether the code is being called by `shiny::runApp`. I’m wondering whether this is a good (enough) test, whether it’s robust to future changes, and whether there’s a better way. In particular, for Shiny Server the function `serverInfo` seems to accomplish what I want but no equivalent seems to exist for running Shiny without Shiny Server.

[:link: Code of my current implementation](https://github.com/klmr/modules/blob/a0a065ccce53d9a67bba7e03bab53d16496090d1/R/module_cache.r#L109-L126)

**Comment by kippandrew** [comment]
I would try posting this question to the shiny-discuss list:

https://groups.google.com/forum/#!forum/shiny-discuss

As this question is not specific to shinyapps.io (the hosting platform).

**Comment by klmr** [comment]
True, thanks.
