### ISSUE TITLE
R 3.2.1 Support

### ISSUE THREAD

**Issue by vnkta** [rstudio/shinyapps#159]
I am trying to deploy an app to shinyapps  and I get the error ...

*Error: Unhandled Exception: Child Task 45992446 failed: Error parsing manifest: Maximum supported R version is: 3.2.0*

I am running RStudio on Windows 7 x64, "R version 3.2.1 (2015-06-18)"

When is it expected support for the latest R version to be added?

Thanks in advance.
Ivan

**Comment by kippandrew** [comment]
We typically add support for R versions about 1 week after they are released. We will be working on this this week.

**Comment by vnkta** [comment]
Great. 
Thanks a lot!

**Comment by jennybc** [comment]
:+1: and :scream: 

I'm trying to submit something to CRAN before UseR and thus must be running R 3.2.1. But it includes Shiny apps, so I'm also getting those into shape and want to make sure they deploy on Shinyapps.io. Suddenly I can't deploy any more.

So I'm caught between a rock and a hard place right now. How soon do you think this will happen?

**Comment by CBarraford** [comment]
we should have this out and ready for people today or tomorrow.

**Comment by CBarraford** [comment]
We've just made 3.2.1 available seconds ago, can people give it a try and let me know if it works ok?

**Comment by vnkta** [comment]
Works fine for me.  :+1:

**Comment by jennybc** [comment]
I'm back in business too. Thanks!
