### ISSUE TITLE
Couple of issues with removeAuthorizedUser

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/shinyapps#162]
1- Documentation says:
```
removeAuthorizedUser(user, appDir = getwd(), appName = NULL,
  account = NULL, server = NULL)
Arguments

user	
The user to remove. Can be id or email address.
```

Shouldn't this just be "email"? (same as addAuthorizedUser)

2- Command does not work, no matter what I pass in as argument.  If I use the command without "server" argument (when there is ambiguity), I get the following error:
```
> removeAuthorizedUser(account="fereshteh")
Error: Multiple accounts with the name 'fereshteh' exist. Please specify the server of the account you wish to use.
```
and when I add "server", I still get the same error:
> removeAuthorizedUser(account="fereshteh", server="shinyapps.io")
Error: Multiple accounts with the name 'fereshteh' exist. Please specify the server of the account you wish to use.
```
And here I have added other arguments, and still the same error:
```
> removeAuthorizedUser(account="fereshteh", server="shinyapps.io", user="internalrsuser1@gmail.com")
Error: Multiple accounts with the name 'fereshteh' exist. Please specify the server of the account you wish to use.
> removeAuthorizedUser(account="fereshteh", server="shinyapps.io", user="internalrsuser1@gmail.com", appName="authenticated-app")
Error: Multiple accounts with the name 'fereshteh' exist. Please specify the server of the account you wish to use.
> removeAuthorizedUser(account="fereshteh", server="shinyapps.io", user="internalrsuser1@gmail.com", appName="authenticated-app", appDir=".")
Error: Multiple accounts with the name 'fereshteh' exist. Please specify the server of the account you wish to use.
```

**Comment by fereshtehRS** [comment]
Both of the issues still happen.

First one is just a naming issue; not a big deal.

Second one happens to my account with multiple server/accounts. It doesn't matter what I specify, I cannot remove a user using the command. With other accounts it is fine.

**Comment by kippandrew** [comment]
This should be fixed, but was not merged down to shinyapps package. Also @fereshtehRS can you file future tickets in rsconnect package?
