### ISSUE TITLE
showUsers() does not show account ID for some users

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/shinyapps#163]
This is the result for one of my apps:
```
> showUsers(account="fereshteh", server="shinyapps.io")
     id                     email account
1     7     fereshteh@rstudio.com       8
2 22907 internalrsuser5@gmail.com       8
3 21481 internalrsuser1@gmail.com      NA
```

Not sure why the last user has NA as account ID.

**Comment by kippandrew** [comment]
That means that the user permission is assigned directly to the app (and no the group or account).

**Comment by kippandrew** [comment]
So this is working as intended. But perhaps could benefit from better documentation or labels on the data frame.
