### ISSUE TITLE
Unable to install shinyapps package

### ISSUE THREAD

**Issue by amolsharma99** [rstudio/shinyapps#165]
Trying Steps as explained here -
http://shiny.rstudio.com/articles/shinyapps.html

Installing from RStudio on a Ubuntu 14.04 Machine.
Getting the following Timeout Error -
--
>devtools::install_github('rstudio/shinyapps')
Downloading github repo rstudio/shinyapps@master
Error in curl::curl_fetch_memory(url, handle = handle) : 
Timeout was reached

Have tried cloning a github repo from terminal and was able to do it, so doesn't looks like a network problem. Please help in resolving the issue.

**Comment by kippandrew** [comment]
This issue doesn't specifically look related to shinyapps package, but perhaps a problem with installing packages using devtools. By chance are you running behind a proxy server?

**Comment by kippandrew** [comment]
Closed with no response.
