### ISSUE TITLE
deployApp() error

### ISSUE THREAD

**Issue by samygero** [rstudio/shinyapps#171]
Hello, I have a small problem. I could use some help please.
I have downloaded, unpacked and instaled the shinyapps package manualy. I think it is useful specifying I am trying to deploy the app from a company laptop.
So here is my error:

>setwd("K:/09_Common Data/02_Users/Samy Geronymos/Ressources/Shiny apps/shiny-examples-master/063-superzip-example-Samy")
>shinyapps::deployApp(appName="heatXplorer")
shinyapps::deployApp('K:/09_Common Data/02_Users/Samy Geronymos/Ressources/Shiny apps/shiny-examples-master/063-superzip-example-Samy')
Preparing to deploy application...
Update application currently deployed at
https://heatxplorer.shinyapps.io/063-superzip-example-Samy? [Y/n] Y
DONE
Uploading bundle for application: 52731...
Error: 
* Unable to deploy package dependency 'shinyapps'
   
   The package was installed locally from source. Only packages installed from CRAN,
   BioConductor and GitHub are supported.

So basically I try downloading the package from github but I get tis error

> devtools::install_github("rstudio/shinyapps")
Downloading github repo rstudio/shinyapps@master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

Here is my sessionInfo() output

>sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6       digest_0.6.8      mime_0.3          bitops_1.0-6      R6_2.1.0         
 [6] xtable_1.7-4      git2r_0.10.1      magrittr_1.5      httr_1.0.0        stringi_0.5-5    
[11] curl_0.9.1        xml2_0.1.1        devtools_1.8.0    shinyapps_0.4.1.4 RJSONIO_1.3-0    
[16] tools_3.2.1       stringr_1.0.0     RCurl_1.95-4.7    shiny_0.12.1      httpuv_1.3.2     
[21] rversions_1.0.2   htmltools_0.2.6   memoise_0.2.1   

Thanks

**Comment by kippandrew** [comment]
Why does your application depend on `shinyapps` package? You should not have any calls inside your app to shinyapps package. 

Regardless, it looks like devtools can not contact github. By chance are you behind a proxy server?

**Comment by samygero** [comment]
Hello!

My app on itself does not depend on the "shintapps" package, but I need it to deploy the app on "shinyapps.io".

Yes I'm behind a proxy. this is the code I use to try to configure it; but still without it working:

options(RCurlOptions = list(proxy = "http://username:password@proxy.server:port"))
options(shinyapps.http = "rcurl")

devtools::install_github("rstudio/shinyapps")

Kind regards,
Samy

**Comment by kippandrew** [comment]
You might try:
http://stackoverflow.com/questions/17783686/solution-how-to-install-github-when-there-is-a-proxy

**Comment by samygero** [comment]
Hello kippandrew,

I tweaked a bit the code and this is my new problem. I'putting all the code so that you can check:

     set_config(
         use_proxy(url="http://<username>:<password>@proxy.eib.electrabel.be",port=8080, username=<username>,password=<password>))
> devtools::install_github("rstudio/shinyapps")
Downloading github repo rstudio/shinyapps@master
Installing shinyapps
Installing 2 packages: base64enc, PKI
package ‘base64enc’ successfully unpacked and MD5 sums checked
package ‘PKI’ successfully unpacked and MD5 sums checked
"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL  \
  "C:/Users/CFH536/AppData/Local/Temp/RtmpwxKCw5/devtoolsc982ed4484/rstudio-shinyapps-688a4ac"  \
  --library="C:/Users/CFH536/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'shinyapps' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (shinyapps)
Reloading installed shinyapps

Attaching package: ‘shinyapps’

The following objects are masked from ‘package:shiny’:

    hr, serverInfo
> options(RCurlOptions = list(proxy = "http://<username>:<password>@proxy.eib.electrabel.be:8080"))
> options(shinyapps.http = "rcurl")
> shinyapps::setAccountInfo(name='heatxplorer', token=<token>,
                          secret=<secret>)
> shinyapps::deployApp('X:/02_0124/01_CEEME/01_SEER/02_ActivityFinite/FV_0046_BES Europe Teasers/04. Project Documents/Waste Heat Potential/Hackathon/R Code/Shiny')
Preparing to deploy application...DONE
Uploading bundle for application: 54530...
Detecting system locale ... en_US
DONE
Deploying bundle: 235902 for application: 54530 ...
Waiting for task: 64847296
  building: Parsing manifest
  building: Building image: 231361
################################ Begin Task Log ################################ 
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 64847298 error: Unhandled Exception: HTTP 599: Stream closed

**Comment by kippandrew** [comment]
We were affected by an [Amazon S3 outage](https://groups.google.com/forum/#!forum/shinyapps-users) this morning, which was casing deployments to fail. You should try deploying your app again. Sorry for the trouble.
