### ISSUE TITLE
Connection Refused for Shinyapp Authorization - Proxy? Firewall?

### ISSUE THREAD

**Issue by brennn1** [rstudio/shinyapps#175]
When I try to authorize my account for shinyapps, I receive the following error:

`Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to api.shinyapps.io port 443: Connection refused`
I know that it has something to do with my proxy or firewall settings, but I do not know how to get around this.

I am not sure how to specify a proxy for \code{rcurl} and \code{curl} connections - as I think this may be the fix?

Any help is appreciated!

**Comment by kippandrew** [comment]
It's usually pretty simple to get the proxy server configured properly. You can read the docs by doing:

```
library(shinyapps)
?rsconnectProxies
```

**Comment by brennn1** [comment]
Hi Andy,

I've read through this documentation, but I am not sure where to start.  I'm not sure what to put into:
`Sys.setenv(http_proxy = "http://proxy.example.com")`.  What replaces `http://proxy.example.com?

**Comment by kippandrew** [comment]
Typically this information is provided by your network administrator. Are you on a campus or corporate network?

**Comment by brennn1** [comment]
I am on a corporate network.  What specifically should I ask my network administrator for?

If I cannot host on Shiny Server or `shinyapps.io`, am I able to host over a Windows based server that is on my network?  Are there any documented resources for publishing a Shiny app, without using a Shiny based solution?  

I found this Overflow: http://stackoverflow.com/questions/26799722/hosting-and-setting-up-own-shiny-apps-without-shiny-server

**Comment by kippandrew** [comment]
I think you'll probably want to use `shinyapps.io` or `shiny-server` to host your shinyapps. Getting shinyapps.io setup should be straight forward once you have your proxy server settings figured out.

I would ask your administrator for your "proxy server address" and "proxy server credentials". The credentials are sometimes the same as Windows username and password, but that depends on your network setup. 

Sometimes, you can also get this info by looking through the "Internet Explorer" settings, but I can not confirm that since I do not use Windows.

**Comment by brennn1** [comment]
Hi Andy,

I found our proxy address.  My question is...now that I have my proxy server address, should I just run `Sys.setenv(http_proxy = "MY_PROXY_ADDRESS")`?

Thanks for the help!  I found the proxy address in my IE `LAN Settings`.

**Comment by kippandrew** [comment]
I would try that. You might also need a username, and password.

**Comment by brennn1** [comment]
Sounds good, I'll try that and see if it works.

And finally, should I specify a port number?  Do you know which port I should specify?  Should it be 443 because of the error message here: `Failed to connect to api.shinyapps.io port 443: Connection refused`?  Or should I specify a port like `8080`?

**Comment by kippandrew** [comment]
You should use the port of your proxy server.

**Comment by brennn1** [comment]
Andy, thanks for your help.  I fixed my problem.  

For those who encounter something similar, this is what I did:
`options(shinyapps,http = "rcurl")`
`options(RCurlOptions = list(proxy = "http://ENTER_YOUR_PROXY_HERE:8080")`

I found my proxy in Internet Explorer.  Open `IE -> Internet Options -> Security -> LAN Settings` and all of the relevant information is under `proxy server`.
