### ISSUE TITLE
error: Building package: zlibbioc

### ISSUE THREAD

**Issue by Liuy12** [rstudio/shinyapps#176]
I am trying to deploy my app to shinyapp.io. Everything works fine few days ago. But when I deploy my app today, I got this error "error: Building package: zlibbioc" and then "Error: Unhandled Exception: Child Task 78936089 error: Unhandled Exception: "

I tried to install a earlier version of "zlibbioc", but still couldn't solve this problem. Any suggestions? Here is my `sessioninfo()`

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] zlibbioc_1.14.0       BiocInstaller_1.19.14 knitr_1.11           

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1       digest_0.6.8      bitops_1.0-6      mime_0.4         
 [5] R6_2.1.1          xtable_1.7-4      formatR_1.2       magrittr_1.5     
 [9] stringi_0.5-5     shinyapps_0.4.1.4 RJSONIO_1.3-0     tools_3.2.2      
[13] stringr_1.0.0     RCurl_1.95-4.7    shiny_0.12.2      httpuv_1.3.3     
[17] htmltools_0.2.6  
```

**Comment by CBarraford** [comment]
I was able to find the error on the shinyapps.io server side.

```
SSLError: [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

Looking further, it seems we tried to download a version that doesn't exist, the url gives a 404.
`https://bioconductor.org/packages/3.2/bioc/src/contrib/zlibbioc_1.14.0.tar.gz`

**Comment by CBarraford** [comment]
I can find version `1.15`, but not `1.14`. @Liuy12 can you try upgrading your zlibbioc to version 1.15 and try again?

**Comment by Liuy12** [comment]
@CBarraford , thanks very much for your response!

I think because of the fact that bioconductor is going to release new version of all packages, the most up to date version from github of many packages are not working properly! Right now, I down-grade all bioconductor-related pacakges to 3.1 version, then everything works like a charm.
