### ISSUE TITLE
Error while installing shinyapp package from github

### ISSUE THREAD

**Issue by varshaaraman** [rstudio/shinyapps#184]
I tried to install shinyapp from github. But I ended up getting the following error : Downloading GitHub repo rstudio/shinyapps@master Installing shinyapps "C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD \ INSTALL \ "C:/Users/varshaa/AppData/Local/Temp/RtmpC637kP/devtools1b6ce932ff6/rstudio-shinyapps-688a4ac" \ --library="C:/Users/varshaa/Documents/R/win-library/3.2" --install-tests

Error: Command failed (65535) When I checked devtools1b6ce932ff6 , it was empty.Kindly help solving this issue

**Comment by kippandrew** [comment]
I think this a devtools issue:

https://github.com/hadley/devtools/issues/857
