### ISSUE TITLE
Configure App size

### ISSUE THREAD

**Issue by debsush** [rstudio/shinyapps#188]
Hi,

I am currently using the free version of shinyapps. 
When I tried the command rsconnect::configureApp("APPNAME", size="large"), I get the message "attempt to apply non-function".
 Is it possible for me to have a shinyapp with xlarge configuration in the free version.  If yes, then what am I doing wrong in the above statement

**Comment by kippandrew** [comment]
The free plan is limited to 1GB (large) which is the default. 

Regardless when running the command, I assume you replaced "APPNAME" with the name of your app?
