### ISSUE TITLE
Shiny app turns grey when deployed, works fine locally

### ISSUE THREAD

**Issue by rpbscott** [rstudio/shinyapps#190]
I have the same problem that was reported in shinyapps issue #133, but no errors are outputted when I run shinyapps::showLogs()...(see [this stackoverflow post] (http://stackoverflow.com/questions/34841795/rs-shiny-app-goes-grey-when-deployed-works-fine-locally) for the full output). I've also tried increasing the size of the application instance and decreasing the number of workers per application instance as is recommend [here]  (http://shiny.rstudio.com/articles/scaling-and-tuning.html). I have a feeling memory usage isn't the problem because one of my apps is extremely simple and the calculations it makes are done within a second or two when run locally. I've also checked out the memory usage of the apps on the shiny dashboard and the usage is no where near the memory limit.

Any help is GREATLY appreciated. [Here's] (https://rosemarie-p-b-scott.shinyapps.io/OM_2266/) an example of one of the problematic shiny apps. This one takes a bit longer to turn grey.

**Comment by kippandrew** [comment]
I played with this app a bit, but I've not seen any client disconnects (gray screen). What steps do I need to perform to reproduce the problem?

**Comment by rpbscott** [comment]
Thanks for your reply! It's grey'd out for me when I've moved the toggle button a few times and the left it open for a period of time. I'll test it out today and give you a specific length of time before it tends to turn grey.

**Comment by rpbscott** [comment]
Hi Andy, OK so I navigated to my app linked to above. Then I changed the toggle value (titled 'Baseline proportion') 4 times. Then I left the tab open (in my Chrome browser) and after about 18 mins the app turned grey and stopped responding. Again, I see no error messages in the logs.

**Comment by kippandrew** [comment]
By default an application will close an idle connection after 15 minutes of inactivity. This means if you open an application, and do not interact with it for 15 minutes, you will see a disconnect (gray screen). You should be able to confirm this by viewing the status message in the javascript console for your browser. This parameter can be adjusted if necessary.

**Comment by rpbscott** [comment]
Gotcha, thanks. I've seen that parameter before. OK, let me mess with my other app that's been greying out is less time. I'm almost positive it's greyed out in under 5 minutes before. I'll comment here describing the event once I can observe it.

**Comment by rpbscott** [comment]
OK, in my other app, the screen turned grey 22 seconds after I opened it. Here's what was printed in the javascript console:
Tue Jan 19 2016 21:16:44 GMT-0800 (PST): Connection closed. Info: {"type":"close","code":1000,"reason":"Normal closure","wasClean":true}
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by kippandrew** [comment]
Can you send me the URL for this app that is crashing?

**Comment by rpbscott** [comment]
Sure, just sent it to you privately through your rstudio email.

**Comment by carometrix** [comment]
Hi I have the exact same problem as the one described above. My app is regularly crashing (becoming gray) on the server, not locally, and I can't figure out any specific pattern. It is not due to memory or CPU usage, neither on the standard logout time (which is 15 minutes for my app, but the problem occurs way before that). Any chance someone solved the issue? Thank you in advance!!

**Comment by rpbscott** [comment]
Hey! So my problem was pretty specific to my app. I had a bunch of images that I was uploading via img() calls in the ui script. Andy and his team came up with two hypotheses for what was going on: 1) Because it can take a while for the image downloads to complete, in some cases, this causes the server to think the client (aka the browser) has disconnected, which will show the gray screen. Without getting into too many details, this is because R (and thus shiny) is single threaded, and can only process one request at time. Because the server is busy processing the image download, it can not process the other requests and the server thinks the client went away. 2) The browser was running out of concurrent http requests to the server--since they're all busy fetching images, there's no connection left for SockJS to talk to the server.

Proposed solutions:
1) resize the images to a smaller size
2) look into is moving the images off of the shinyapp server and onto a cheap webhost, or Amazon EC2, or even imgur.com, and have your Shiny app point to those hosts.
3) Another option that would involve more R and less host-related stuff would be instead of embedding image tags directly into your UI, instead use imageOutput/renderImage for each image.

I've tried 1) for now and it seems to have done the trick! I needed to resize them quite a bit smaller. I also strongly recommend checking out the javascript console as Andy previously suggested to me in this thread. 

carometrix, why don't you paste here the errors you're getting in the javascript console after the crashes?

**Comment by kippandrew** [comment]
@carometrix Do you mind posting your question to the [shinyapps-users discussion group](https://groups.google.com/forum/#!forum/shinyapps-users) along with your application URL and output from `rsconnect::showLogs()` ? 

As @rpbscott mentioned, this ticket was likely for a different issue.

**Comment by carometrix** [comment]
@rpbscott thank you for your quick answer! @kippandrew sure!

**Comment by GratienDSX** [comment]
Hi @kippandrew, following up @carometrix comment I just sent you the link privately through your rstudio email, and posted the question on the shinyapps users group.

**Comment by mnozary** [comment]
I have the same problem with Rmd files. I have a Rmd file which should process a CSV file and produce a report, but I think because it's too long to create the report, I see a gray screen and disconnected from the server. How can I solve this problem? In the case of an image they can use other hosts but how about Rmd file?

**Comment by jienagu** [comment]
I have the same problem, @mnozary ! If the workload is heavy, it is always disconnected from the server.

Do you figure out some ways to solve this problem?

**Comment by kippandrew** [comment]
@jienagu Can I suggest reporting the problem you are seeing on the shinyapps.io discussion list?

https://groups.google.com/forum/#!forum/shinyapps-users
