### ISSUE TITLE
When to expect support for R version 3.2.4?

### ISSUE THREAD

**Issue by pssguy** [rstudio/shinyapps#196]
On deploying

Error: Unhandled Exception: Child Task 167465936 failed: Error parsing manifest: Maximum supported R version is: 3.2.3
Execution halted

**Comment by kippandrew** [comment]
We typically add support a few days after its released. You can follow this thread here for updates:

https://groups.google.com/forum/#!topic/shiny-discuss/XlakWblu7CY

**Comment by pssguy** [comment]
Tx. looks good now
