### ISSUE TITLE
To increase application size from 1 GB to 2 GB

### ISSUE THREAD

**Issue by AgazW** [rstudio/shinyapps#208]
I deployed my application and it works fine for most of the functionalities. However, for one of the functionality, the data size is a bit large and the application goes blur after some time. I am sure the reason is more size of my application as the application size is limited to 1 GB for free users. I would like to know if you can please increase my limit to 2 GB.

**Comment by kippandrew** [comment]
With the shinyapps.io Basic plan and above, you can use up to 8GB of memory. All the details can be found here: http://www.shinyapps.io/#pricing
