### ISSUE TITLE
delete an app

### ISSUE THREAD

**Issue by yihui** [rstudio/shinyapps#23]
It seems there is no way of deleting an app. It is not possible with either R functions or the web interface (not implemented yet?).

**Comment by yimihua2013** [comment]
same question here. Wish there will be a "delete" function soon.

**Comment by tleitch** [comment]
archive removes from view, which is probably better than delete, unless you want to remove the data altogether

**Comment by khughitt** [comment]
:+1: Delete would be nice.

**Comment by datasourcery** [comment]
Add a delete function please.

**Comment by bengapple** [comment]
If we are at the max of five apps will archive allow us to add another app?

**Comment by CBarraford** [comment]
If you archive an app, you should be able to add a new one.

**Comment by bengapple** [comment]
Thanks.  That is what I did and worked fine.

On Sat, Apr 4, 2015 at 5:24 PM, Chad Barraford <notifications@github.com>
wrote:

> If you archive an app, you should be able to add a new one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rstudio/shinyapps/issues/23#issuecomment-89669616>.
>



-- 
Ben Apple MsIA, CISA, CISSP, CISM, CIA

**Comment by jbkunst** [comment]
:+1:

**Comment by isabeaups** [comment]
Yes! Actually being able to delete and not just archive would be very much appreciated!

**Comment by misanuk** [comment]
Agreed, really need to be able to delete apps!

**Comment by HimanshuBabbar** [comment]
I've reached my maximum limit of applications (is it 7?) Those were test apps, now that i really want to deploy an app, I'm not able to. Any suggestions how to delete the existing apps?

**Comment by kippandrew** [comment]
If you archive an application it doesn't count against your 5 application limit.

Also the good news is, we are very close to releasing the ability to delete apps.

**Comment by jbkunst** [comment]
I'm just able to delete some old apps (first archive, the delete)! Thank you guys!

**Comment by kippandrew** [comment]
Deletes are working now.

**Comment by tleitch** [comment]
Thanks.
